name: Create GitHub Release

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
  push:
    branches:
      - feat/reusable-release-process

permissions:
  contents: write
  id-token: write # For publishing to npm using --provenance

jobs:
  release:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/'))
    uses: ./.github/workflows/publish-npm.yml
    with:
      node-version: 18
    secrets: inherit







